[funfacts]
title = "Wikipedia — did you know?"
url = "https://rss.beehiiv.com/feeds/heCuwnxgoQ.xml"
entrySelector = "#mp-dyk > ul li"
titleSelector = "b"
linkSelector = "b a"

[wikivoyage]
title = "Wikivoyage recommendations"
url = "https://rss.beehiiv.com/feeds/heCuwnxgoQ.xml"
entrySelector = ".jcarousel-wrapper .jcarousel-item"
titleSelector = "h2"
linkSelector = "h2 a"
